# Экономическая задача

**Задача.** Фермер вложил в прошлом году в зерноводство,животноводство и овощеводство всего 2 миллиона денежных единиц и получил 180 тысяч денежных единиц прибыли. В текущем году он собирается увеличить вложения в овощеводство в 3 раза, в животноводство в 2 раза, а вложения в зерноводство оставить на прежнем уровне. На все это фермер выделяет 4
миллиона денежных единиц. Какую прибыль собирается получить фермер в текущем году, если зерноводство приносит 7% прибыли на вложенные средства, животноводство 8% и овощеводство 9 %?

Пусть $x_{1}$, $x_{2}$, $x_{3}$ - вложения фермера в зерноводство, животноводство и в овощеводство в прошлом году (в миллионах денежных единиц). Тогда,

Инвестиции в прошлом году: $x_{1} + x_{2} + x_{3} = 2$<br>Инвестиции в текущем году: $x_{1} + 2x_{2} + 3x_{3} = 4$<br>Прибыль в прошлом году: $0,07x_{1} + 0,08x_{2} + 0,9x_{3} = 0,18$

Получим систему линейных уравнений:
$$
\begin{cases}
x_{1} + x_{2} + x_{3} = 2 \\
x_{1} + 2x_{2} + 3x_{3} = 4 \\
0,07x_{1} + 0,08x_{2} + 0,9x_{3} = 0,18
\end{cases}
$$

В результате имеем систему из трех линейных уравнений с тремя неизвестными. Исследуем данную систему на совместность по теореме
Кронекера-Капелли. Составим расширенную матрицу системы:

$$
\bar{A} = 
\left\lgroup\begin{matrix}
1 & 1 & 1 & \vert & 1 \cr
1 & 2 & 3 & \vert & 4 \cr
0,07 & 0,08 & 0,09 & \vert & 0,18
\end{matrix}\right\rgroup
$$

In [45]:
import numpy as np

slau = np.matrix('1 1 1 1; 1 2 3 4; 0.07 0.08 0.09 0.18')
n, m = slau.shape
print(slau)

[[1.   1.   1.   1.  ]
 [1.   2.   3.   4.  ]
 [0.07 0.08 0.09 0.18]]


Приведем матрицу к ступенчатому виду:

In [46]:
for j in range(n - 1):
    for i in range(n - 1):
        if i < j:
            i = j
        mn = slau[i + 1, j] / slau[j, j]
        slau[i + 1] = slau[i + 1] - slau[j]* mn
print(slau)

[[1.   1.   1.   1.  ]
 [0.   1.   2.   3.  ]
 [0.   0.   0.   0.08]]


Получим:
$$
\left\lgroup\begin{matrix}
1 & 1 & 1 & \vert & 1 \cr
0 & 1 & 2 & \vert & 3 \cr
0 & 0 & 0 & \vert & 0,08
\end{matrix}\right\rgroup
$$

В преобразованной матрице системы последняя строка состоит их нулей. В качестве базисного минора матрицы системы можно выбрать
$$
M_{2} = 
\begin{vmatrix}
1 & 1\\
0 & 1
\end{vmatrix}
 = 1 \ne 0
$$, то есть $r(A) = 2$

In [57]:
rank_a = np.linalg.matrix_rank(slau[:, 0:m -1])
print(f"Ранг матрицы А: {rank_a}")

Ранг матрицы А: 2


В качестве базисного минора расширенной матрицы системы можно выбрать
$$
M_{3} = 
\begin{vmatrix}
1 & 1 & 2\\
0 & 1 & 2\\
0 & 0 & 0,08
\end{vmatrix} = 1 * 1 * 14 = 14 \ne 0
$$, то есть $r(\bar{A}) = 3$

In [58]:
rank_ab = np.linalg.matrix_rank(slau)
print(f"Ранг матрицы АB: {rank_ab}")

Ранг матрицы АB: 3


In [47]:
slau_a = slau[:, 0:m]
slau_b = slau[:, m - 1]

In [48]:
x = np.ones([1, n])
x

array([[1., 1., 1.]])

In [54]:
rank_a = np.linalg.matrix_rank(slau[:, 0:m -1])
rank_ab = np.linalg.matrix_rank(slau)

if rank_a == rank_ab:
    print("Система совместна")
    if rank_a >= m:
        print("Система определена")
        for j in range(n - 1, -1, -1):
            x[0, j] = slau_b[j] / np.sum(slau_a[j, :] * x)
        print(x)
    else:
        print("Система не определена")
else:
    print("Система не совместна, решений нет")

Система не совместна, решений нет


Итак, $r(A) ≠ r(\bar{A})$ следовательно, по теореме Кронекера-Капелли
система несовместна и задача не имеет решений.