# Решение СЛАУ методом Гаусса

Создание расширенной матрицы (А|В)

In [198]:
import numpy as np

n = int(input("Введите количество строк: "))
m = int(input("Введите количество столбцов: "))
slau = np.random.randint(0, 15, size = (n, m + 1))

#slau_b = slau_a[:, m]
print(slau)

Введите количество строк: 4
Введите количество столбцов: 4
[[ 1  9  9  7  5]
 [ 0  5 10  9 12]
 [ 4  1 13  3 14]
 [ 9 13 12 11  6]]


Приведение к треугольному виду

In [199]:
for j in range(n - 1):
    for i in range(n - 1):
        if i < j:
            i = j
        mn = slau[i + 1, j] / slau[j, j]
        slau[i + 1] = slau[i + 1] - slau[j]* mn

Разделение на A и B

In [200]:
slau_a = slau[:, 0:m]
slau_b = slau[:, m]
print(slau_a, slau_b)

[[ 1  9  9  7]
 [ 0  5 10  9]
 [ 0  0 47 38]
 [ 0  0  0 15]] [ 5 12 78 12]


In [201]:
x = np.ones([1, n])
x

array([[1., 1., 1., 1.]])

Нахождение x

In [202]:
rank_a = np.linalg.matrix_rank(slau[:, 0:m])
rank_ab = np.linalg.matrix_rank(slau)

if rank_a == rank_ab:
    print("Система совместна")
    if rank_a >= m:
        print("Система определена")
        for j in range(n - 1, -1, -1):
            x[0, j] = slau_b[j] / np.sum(slau_a[j, :] * x)
        print(x)
    else:
        print("Система не определена")
else:
    print("Система не совместна, решений нет")

Система совместна
Система определена
[[0.24369198 0.53865961 1.00775194 0.8       ]]
